// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPfb7dpp8JG_jgOkZTct4bsaLUhxv-U3I',
    appId: '1:846622288574:web:080c3b978407cc62500cef',
    messagingSenderId: '846622288574',
    projectId: 'ocds-da47e',
    authDomain: 'ocds-da47e.firebaseapp.com',
    databaseURL: 'https://ocds-da47e-default-rtdb.firebaseio.com',
    storageBucket: 'ocds-da47e.appspot.com',
    measurementId: 'G-FHGNY91EQ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANiHVDNjvHHYery_Z_HZa3Tk0XQ1gID4k',
    appId: '1:846622288574:android:f5cb39bf9bd656cd500cef',
    messagingSenderId: '846622288574',
    projectId: 'ocds-da47e',
    databaseURL: 'https://ocds-da47e-default-rtdb.firebaseio.com',
    storageBucket: 'ocds-da47e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfaUkamtqCAuIWKD2zNlBw4-bdV4QV-qY',
    appId: '1:846622288574:ios:a7d69cb90fd8959b500cef',
    messagingSenderId: '846622288574',
    projectId: 'ocds-da47e',
    databaseURL: 'https://ocds-da47e-default-rtdb.firebaseio.com',
    storageBucket: 'ocds-da47e.appspot.com',
    androidClientId: '846622288574-6ctuaeqm55ue4q3qg2h330uh6edes9aa.apps.googleusercontent.com',
    iosClientId: '846622288574-qfkr70iuhakqnl1jguqji3ajuqn5bvt7.apps.googleusercontent.com',
    iosBundleId: 'com.example.checkDeposit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfaUkamtqCAuIWKD2zNlBw4-bdV4QV-qY',
    appId: '1:846622288574:ios:d249044af47607c4500cef',
    messagingSenderId: '846622288574',
    projectId: 'ocds-da47e',
    databaseURL: 'https://ocds-da47e-default-rtdb.firebaseio.com',
    storageBucket: 'ocds-da47e.appspot.com',
    androidClientId: '846622288574-6ctuaeqm55ue4q3qg2h330uh6edes9aa.apps.googleusercontent.com',
    iosClientId: '846622288574-8g8efiegps9eke5015e97ljte49h4f79.apps.googleusercontent.com',
    iosBundleId: 'com.example.checkDeposit.RunnerTests',
  );
}
